# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_openingpage(object):
    def setupUi(self, openingpage):
        openingpage.setObjectName("openingpage")
        openingpage.resize(1242, 529)
        openingpage.setMinimumSize(QtCore.QSize(1242, 529))
        openingpage.setMaximumSize(QtCore.QSize(1242, 529))
        openingpage.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.passask = QtWidgets.QLabel(openingpage)
        self.passask.setGeometry(QtCore.QRect(730, 340, 61, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.passask.setFont(font)
        self.passask.setObjectName("passask")
        self.label = QtWidgets.QLabel(openingpage)
        self.label.setGeometry(QtCore.QRect(840, 460, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.submitbutton = QtWidgets.QPushButton(openingpage)
        self.submitbutton.setGeometry(QtCore.QRect(1090, 420, 101, 31))
        self.submitbutton.setObjectName("submitbutton")
        self.lineEdit = QtWidgets.QLineEdit(openingpage)
        self.lineEdit.setGeometry(QtCore.QRect(840, 410, 240, 40))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(openingpage)
        self.label_2.setGeometry(QtCore.QRect(710, 70, 430, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(openingpage)
        self.label_3.setGeometry(QtCore.QRect(710, 130, 430, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(openingpage)
        self.label_4.setGeometry(QtCore.QRect(710, 190, 471, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(openingpage)
        self.label_5.setGeometry(QtCore.QRect(710, 250, 271, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(openingpage)
        self.lineEdit_2.setGeometry(QtCore.QRect(840, 350, 240, 40))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(openingpage)
        self.label_6.setGeometry(QtCore.QRect(730, 410, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(openingpage)
        self.label_7.setGeometry(QtCore.QRect(30, 70, 611, 451))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../SIH PYQT/secura.PNG"))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(openingpage)
        self.label_8.setGeometry(QtCore.QRect(30, 0, 211, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")

        self.retranslateUi(openingpage)
        QtCore.QMetaObject.connectSlotsByName(openingpage)

    def retranslateUi(self, openingpage):
        _translate = QtCore.QCoreApplication.translate
        openingpage.setWindowTitle(_translate("openingpage", "Dialog"))
        self.passask.setText(_translate("openingpage", "UserID"))
        self.label.setText(_translate("openingpage", "(Password will not be stored)"))
        self.submitbutton.setText(_translate("openingpage", "Submit"))
        self.label_2.setText(_translate("openingpage", "Welcome to Secura, we aim to provide an "))
        self.label_3.setText(_translate("openingpage", " easy and intuitive way to enchance the"))
        self.label_4.setText(_translate("openingpage", "security features, making your organization"))
        self.label_5.setText(_translate("openingpage", "more secure."))
        self.label_6.setText(_translate("openingpage", "Password"))
        self.label_8.setText(_translate("openingpage", "Secura"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    openingpage = QtWidgets.QDialog()
    ui = Ui_openingpage()
    ui.setupUi(openingpage)
    openingpage.show()
    sys.exit(app.exec_())
