# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'escutcheeon.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.uic import loadUi
from PyQt5.QtWidgets import QDialog,QApplication,QLineEdit
from PyQt5.QtGui import QFont
import sys
import pysondb as ps
from hardener import hardener
from hardener import access
from hardener import makeDB
from lynisInfo import sysinf
from lynisInfo import scaninf
from lynisInfo import suggestions
from lynisInfo import warnings
from lynisInfo import remove_ansi_escape_codes
import webbrowser

class Ui_Openingpage(QDialog):
    def __init__(self):
        super(Ui_Openingpage,self).__init__()
        loadUi("escutcheeon.ui",self)
        self.pushButton.clicked.connect(self.gotoSudoRun)
    def gotoSudoRun(self):
        widget1.setCurrentIndex(1)
class Ui_Dialog(QDialog):
    def __init__(self):
        super(Ui_Dialog,self).__init__()
        loadUi("sudoinput.ui",self)
        self.submitbutton.clicked.connect(self.getpass)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)

    def getpass(self):
        password=self.lineEdit.text()
        print(password)
        a = access(password)
        widget1.setCurrentIndex(widget1.currentIndex()+1)

class Ui_home(QDialog):
    def __init__(self, d,s):
        super(Ui_home,self).__init__()
        loadUi("homescreen.ui",self)
        self.score = s
        self.details = d

        self.benchmarkingbutton.clicked.connect(self.gotoBenchmarking)
        self.hardeningbutton.clicked.connect(self.gotoHardening)
        self.progversioninput.setText(self.details[0])
        self.progversioninput.setFont(QFont('Segoe UI ',11))
        self.osinput.setText(self.details[1])
        self.osinput.setFont(QFont('Segoe UI ',11))
        self.osnameinput.setText(self.details[2])
        self.osnameinput.setFont(QFont('Segoe UI ',11))
        self.osversioninput.setText(self.details[3])
        self.osversioninput.setFont(QFont('Segoe UI ',11))
        self.kernelversioninput.setText(self.details[4])
        self.kernelversioninput.setFont(QFont('Segoe UI ',11))
        self.hardwareplatforminput.setText(self.details[5])
        self.hardwareplatforminput.setFont(QFont('Segoe UI ',11))
        self.hostnameinput.setText(self.details[6])
        self.hostnameinput.setFont(QFont('Segoe UI ',11))
        self.helpbutton.clicked.connect(self.gotoPage)
        self.lcdNumber.display(int(self.score))
    def gotoPage(self):
        webbrowser.open("https://pranav-p92.github.io/HELP-PAGE/index.html")

    def gotoBenchmarking(self):
        widget1.setCurrentIndex(widget1.currentIndex()+1)
    def gotoHardening(self):
        widget1.setCurrentIndex(4)
    def get_deets(self, d):
        self.details = d
    def show_deets(self):
        print(self.details)

class Ui_benchmarking(QDialog):
    def __init__(self, a, b, c):
        self.deets = a
        self.warnings = b
        self.suggestions = c
        super(Ui_benchmarking,self).__init__()
        loadUi("benchmarking.ui",self)
        self.homebutton.clicked.connect(self.gotoHome)
        self.hardeningbutton.clicked.connect(self.gotoHardening)
        self.hardeningiput.setText(self.deets[0])
        self.hardeningiput.setFont(QFont('Segoe UI Semilight',12))
        self.testsperformedinput.setText(self.deets[1])
        self.testsperformedinput.setFont(QFont('Segoe UI Semilight',12))
        self.pluginsinput.setText(self.deets[2])
        self.pluginsinput.setFont(QFont('Segoe UI Semilight',12))
        self.textBrowser.setAcceptRichText(True)
        self.textBrowser.append(self.warnings)
        self.textBrowser_2.setAcceptRichText(True)
        self.textBrowser_2.append(self.suggestions)
        self.helpbutton.clicked.connect(self.gotoPage)
    def gotoPage(self):
        webbrowser.open("https://pranav-p92.github.io/HELP-PAGE/index.html")
    def get_deets(self, d):
        self.deets = d
    def get_warnings(self,s):
        self.warnings = s
    def get_suggestions(self,s):
        self.suggestions = s
    def gotoHardening(self):
        widget1.setCurrentIndex(4)
    def gotoHome(self):
        widget1.setCurrentIndex(2)
    def show_deets(self):
        print(self.deets)

class Ui_Hardening(QDialog):
    def __init__(self):
        self.db = ps.getDb('bool.json')
        self.dict={'Password Policies' : "" ,"Remove Unecessary Packages" : "" ,'UFW' : "" ,'fail2ban' : "" ,'USB Storage Access' : "" ,'TOR Service' : "" ,}
        super(Ui_Hardening,self).__init__()
        loadUi("hardeningbasic.ui",self)
        self.homebutton.clicked.connect(self.gotoHome)
        self.savebutton.clicked.connect(self.Save)
        self.advanced.clicked.connect(self.gotoAdvanced)
        self.hardenbutton.clicked.connect(self.Harden)
        self.benchmarkingbutton.clicked.connect(self.gotoBenchmarking)
        self.helpbutton.clicked.connect(self.gotoPage)
    def gotoPage(self):
        webbrowser.open("https://pranav-p92.github.io/HELP-PAGE/index.html")
    def Harden(self):
        hard = hardener()
        hard.harden()
        remove_ansi_escape_codes()
    def gotoBenchmarking(self):
        widget1.setCurrentIndex(3)
    def gotoAdvanced(self):
        widget1.setCurrentIndex(5)
    def Save(self):
        #remove orphan packages
        if self.rupyes.isChecked()==True or self.rupno.isChecked()==True:
            self.db.updateByQuery({'name':'rmpk'},{'bool':'True'})
        elif self.ppno_2.isChecked()==True:
            self.db.updateByQuery({'name':'rmpk'},{'bool':'None'})
        #password policies
        if self.ppyes.isChecked()==True:
            self.db.updateByQuery({'name':'pwdp'},{'bool':'True'})
        elif self.ppno.isChecked()==True:
            self.db.updateByQuery({'name':'pwdp'},{'bool':'None'})
        elif self.ppno_2.isChecked()==True:
            self.db.updateByQuery({'name':'pwdp'},{'bool':'None'})
        #ufw
        if self.ufwyes.isChecked()==True:
            self.db.updateByQuery({'name':'ufwI'},{'bool':'True'})
            self.db.updateByQuery({'name':'ufwE'},{'bool':'True'})
        elif self.ufwno.isChecked()==True:
            self.db.updateByQuery({'name':'ufwD'},{'bool':'None'})
        elif self.ppno_4.isChecked()==True:
            self.db.updateByQuery({'name':'ufwD'},{'bool':'None'})
            self.db.updateByQuery({'name':'ufwI'},{'bool':'None'})
            self.db.updateByQuery({'name':'ufwE'},{'bool':'None'})
        #fail2ban
        if self.fail2banyes.isChecked()==True:
            self.db.updateByQuery({'name':'f2bE'},{'bool':'True'})
        elif self.fail2banno.isChecked()==True:
            self.db.updateByQuery({'name':'f2bD'},{'bool':'True'})
        elif self.ppno_5.isChecked()==True:
            self.db.updateByQuery({'name':'f2bE'},{'bool':'None'})
            self.db.updateByQuery({'name':'f2bD'},{'bool':'None'})
        #usb storage
        if self.usbsayes.isChecked()==True:
            self.db.updateByQuery({'name':'usbE'},{'bool':'True'})
        elif self.usbno.isChecked()==True:
            self.db.updateByQuery({'name':'usbE'},{'bool':'None'})
        elif self.ppno_6.isChecked()==True:
            self.db.updateByQuery({'name':'usbE'},{'bool':'None'})
        #tor
        if self.usbyes.isChecked()==True:
            self.db.updateByQuery({'name':'torD'},{'bool':'None'})
        elif self.usbno_2.isChecked()==True:
            self.db.updateByQuery({'name':'torD'},{'bool':'None'})
        elif self.ppno_7.isChecked()==True:
            self.db.updateByQuery({'name':'torD'},{'bool':'None'})

    def gotoHome(self):
        widget1.setCurrentIndex(2)

class Ui_hardeningadvanced(QDialog):
    def __init__(self):
        self.db = ps.getDb('bool.json')
        super(Ui_hardeningadvanced,self).__init__()
        loadUi("hardeningadvanced.ui",self)
        self.homebutton.clicked.connect(self.gotoHome)
        self.benchmarkingbutton.clicked.connect(self.gotoBenchmarking)
        self.hardeningbutton.clicked.connect(self.gotoHardening)
        self.pushButton.clicked.connect(self.configAD)
        self.helpbutton.clicked.connect(self.gotoPage)
    def gotoPage(self):
        webbrowser.open("https://pranav-p92.github.io/HELP-PAGE/index.html")
    def configAD(self):
        #ports
        if self.lineEdit.text():
            if self.radioButton.isChecked()==True:
                self.db.updateByQuery({'name':'ufwAP'},{'bool':'True','args':self.lineEdit.text()},)
            elif self.radioButton_2.isChecked()==True:
                self.db.updateByQuery({'name':'ufwBP'},{'bool':'True','args':self.lineEdit.text()})
        else:
            self.db.updateByQuery({'name':'ufwAP'},{'bool':'None', 'args':'None'})
            self.db.updateByQuery({'name':'ufwBP'},{'bool':'None', 'args':'None'})
        #block ips
        if self.lineEdit_2.text():
            self.db.updateByQuery({'name':'ufwBI'},{'bool':'True', 'args': self.lineEdit_2.text()})
        #whitelist ips
        if self.lineEdit_3.text():
            self.db.updateByQuery({'name':'ufwAI'},{'bool':'True', 'args': self.lineEdit_3.text()})
        if self.lineEdit_4.text():
            self.db.updateByQuery({'name':'ufwDel'},{'bool':'True', 'args': self.lineEdit_4.text()})

    def gotoHome(self):
        widget1.setCurrentIndex(2)
    def gotoBenchmarking(self):
        widget1.setCurrentIndex(3)
    def gotoHardening(self):
        widget1.setCurrentIndex(4)






#hard = hardener()
#remove_ansi_escape_codes()

first = sysinf()
second = scaninf()
third = warnings()
fourth = suggestions()

app = QApplication(sys.argv)
widget1=QtWidgets.QStackedWidget()
ui_openingpage=Ui_Openingpage()
ui_dialog=Ui_Dialog()
ui_home=Ui_home(first, second[0])
ui_benchmarking=Ui_benchmarking(second, third, fourth)
ui_hardening=Ui_Hardening()
ui_hardeningadvanced=Ui_hardeningadvanced()

widget1.addWidget(ui_openingpage)
widget1.addWidget(ui_dialog)
widget1.addWidget(ui_home)
widget1.addWidget(ui_benchmarking)
widget1.addWidget(ui_hardening)
widget1.addWidget(ui_hardeningadvanced)

widget1.setFixedWidth(1242)
widget1.setFixedHeight(529)

makeDB()

widget1.show()



try:
    sys.exit(app.exec())
except Exception as e:
    print("An error occurred:", str(e))
