# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'escutcheeon.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import webbrowser
import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.uic import loadUi
from PyQt5.QtWidgets import QDialog,QApplication,QLineEdit
from PyQt5.QtGui import QFont
import subprocess as sp
import pysondb as ps
from hardener import hardener
from hardener import makeDB
from lynisInfo import sysinf
from lynisInfo import scaninf
from lynisInfo import suggestions
from lynisInfo import warnings
from lynisInfo import remove_ansi_escape_codes


class Ui_openingpage(QDialog):
    def __init__(self):
        super(Ui_openingpage,self).__init__()
        loadUi("loginpage.ui",self)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.submitbutton.clicked.connect(self.getdetails)
        self.Registerbutton.clicked.connect(self.goToRegister)

    def goToRegister(self):
        register = Ui_registration()
        widget1.addWidget(register)
        widget1.setCurrentWidget(register)

    def get_passkey(self):
        with sqlite3.connect('password.db') as conn:
            cur=conn.cursor()
        with open('user.txt') as f:
            data=f.read()
        cur.execute("SELECT * FROM passkey WHERE userid=(?)", (data,))
        data1=cur.fetchall()
        conn.commit()
        return data1[0][1]

    def getdetails(self):
        userid=self.lineEdit_2.text()
        password=self.lineEdit.text()
        with sqlite3.connect('password.db') as conn:
            cur=conn.cursor()

        with open('user.txt', 'w') as f:
            f.write(userid)
        password1=self.get_passkey()
        cur.execute("SELECT * FROM passkey WHERE userid=(?)", (userid,))
        data=cur.fetchall()
        conn.commit()
        if data:
            if password==password1:
                sudo = Ui_sudo()
                widget1.addWidget(sudo)
                widget1.setCurrentWidget(sudo)

            else:
                self.warninglabel.setText("Passwords do not match")
        else:
            self.warninglabel.setText("User does not exist")
        

class Ui_registration(QDialog):
    def __init__(self):
        super(Ui_registration,self).__init__()   
        loadUi('registrationpage.ui', self)   
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Registerbutton.clicked.connect(self.savedetails)

    def savedetails(self):
        userid=self.lineEdit_2.text()
        password=self.lineEdit_3.text()
        password1=self.lineEdit_4.text()

        with sqlite3.connect('password.db') as conn:
            cur=conn.cursor()
            cur.execute("""CREATE TABLE IF NOT EXISTS passkey(
                        userid text,
                        pass text
                        )""")
            conn.commit()

    
        cur.execute("SELECT * FROM passkey WHERE userid=(?)", (userid,))
        check=cur.fetchall()
        conn.commit()
        if check:
            self.warninglabel.setText("User already exists")

        else:
            if password==password1:
                cur.execute("INSERT INTO passkey VALUES(?,?)", (userid,password,))
                conn.commit()
                openingpage=Ui_openingpage()
                widget1.addWidget(openingpage)
                widget1.setCurrentWidget(openingpage)
            else:
                self.warninglabel.setText("Passwords Do not match")

class Ui_sudo(QDialog):
    def __init__(self):
        super(Ui_sudo, self).__init__()
        loadUi("sudoinput.ui",self)
        self.submitbutton.clicked.connect(self.handleSudo)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
    def handleSudo(self):
        f = sysinf()
        s = scaninf()
        home = Ui_home(f,s[0], self.lineEdit.text())
        widget1.addWidget(home)
        widget1.setCurrentWidget(home)

class Ui_home(QDialog):
    def __init__(self, d,s, su):
        super(Ui_home,self).__init__()
        loadUi("homescreen.ui",self)
        self.score = s
        self.details = d
        self.sudo = su

        self.benchmarkingbuttton.clicked.connect(self.gotoBenchmarking)
        self.hardeningbutton.clicked.connect(self.gotoHardening)
        self.homebutton_2.clicked.connect(self.gotoAdvanced)
        self.progversioninput.setText(self.details[0])
        self.progversioninput.setFont(QFont('Segoe UI ',11))
        self.osinput.setText(self.details[1])
        self.osinput.setFont(QFont('Segoe UI ',11))
        self.osnameinput.setText(self.details[2])
        self.osnameinput.setFont(QFont('Segoe UI ',11))
        self.osversioninput.setText(self.details[3])
        self.osversioninput.setFont(QFont('Segoe UI ',11))
        self.kernelversioninput.setText(self.details[4])
        self.kernelversioninput.setFont(QFont('Segoe UI ',11))
        self.hardwareplatforminput.setText(self.details[5])
        self.hardwareplatforminput.setFont(QFont('Segoe UI ',11))
        self.hostnameinput.setText(self.details[6])
        self.hostnameinput.setFont(QFont('Segoe UI ',11))
        self.helpbutton.clicked.connect(self.gotoPage)
        self.lcdNumber.display(int(self.score))
    def gotoPage(self):
        webbrowser.open("https://sih-grind.github.io/Help-Page/")

    def gotoBenchmarking(self):
        second = scaninf()
        third = warnings()
        fourth = suggestions()
        benchmarking=Ui_benchmarking(second, third, fourth, self.sudo)
        widget1.addWidget(benchmarking)
        widget1.setCurrentWidget(benchmarking)

    def gotoHardening(self):
        hardening=Ui_Hardening(self.sudo)
        widget1.addWidget(hardening)
        widget1.setCurrentWidget(hardening)

    def gotoAdvanced(self):
        process = sp.Popen([f'sudo -S ufw status numbered'], stdin = sp.PIPE, stdout=sp.PIPE, shell=True)
        output, error = process.communicate("chai@1234".encode())
        process.wait()
        hardening=Ui_hardeningadvanced(output.decode(),self.sudo)
        widget1.addWidget(hardening)
        widget1.setCurrentWidget(hardening)

    def get_deets(self, d):
        self.details = d

    def show_deets(self):
        print(self.details)

class Ui_benchmarking(QDialog):
    def __init__(self, a, b, c, su):
        self.deets = a
        self.w = b
        self.s = c
        self.sudo = su
        super(Ui_benchmarking,self).__init__()
        loadUi("benchmark.ui",self)
        self.homebutton.clicked.connect(self.gotoHome)
        self.hardeningbutton.clicked.connect(self.gotoHardening)
        self.hardeningbutton_2.clicked.connect(self.gotoAdvanced)
        self.label_6.setText(self.deets[0])
        self.label_6.setFont(QFont('Segoe UI Semilight',12))
        self.label_8.setText(self.deets[1])
        self.label_8.setFont(QFont('Segoe UI Semilight',12))
        self.label_9.setText(self.deets[2])
        self.label_9.setFont(QFont('Segoe UI Semilight',12))
        self.textBrowser.setAcceptRichText(True)
        self.textBrowser.append(str(self.w))
        self.textBrowser_2.setAcceptRichText(True)
        self.textBrowser_2.append(str(self.s))
        self.helpbutton.clicked.connect(self.gotoPage)

    def gotoPage(self):
        webbrowser.open("https://sih-grind.github.io/Help-Page/")

    def get_deets(self, d):
        self.deets = d

    def get_warnings(self,s):
        self.warnings = s

    def get_suggestions(self,s):
        self.suggestions = s

    def gotoHardening(self):
        hardening=Ui_Hardening(self.sudo)
        widget1.addWidget(hardening)
        widget1.setCurrentWidget(hardening)

    def gotoHome(self):
        f = sysinf()
        s = scaninf()
        home = Ui_home(f,s[0],self.sudo)
        widget1.addWidget(home)
        widget1.setCurrentWidget(home)

    def gotoAdvanced(self):
        process = sp.Popen([f'sudo -S ufw status numbered'], stdin = sp.PIPE, stdout=sp.PIPE, shell=True)
        output, error = process.communicate("chai@1234".encode())
        process.wait()
        hardening=Ui_hardeningadvanced(output.decode(),self.sudo)
        widget1.addWidget(hardening)
        widget1.setCurrentWidget(hardening)

    def show_deets(self):
        print(self.deets)

class Ui_Hardening(QDialog):
    def __init__(self, su):
        self.db = ps.getDb('bool.json')
        self.dict={'Password Policies' : "" ,"Remove Unecessary Packages" : "" ,'UFW' : "" ,'fail2ban' : "" ,'USB Storage Access' : "" ,'TOR Service' : "" ,}
        self.sudo = su
        super(Ui_Hardening,self).__init__()
        loadUi("harden.ui",self)
        self.homebutton.clicked.connect(self.gotoHome)
        self.hardeningbutton_2.clicked.connect(self.gotoAdvanced)
        self.savebutton.clicked.connect(self.Save)
        self.hardenbutton.clicked.connect(self.Harden)
        self.benchmarkingbuttton.clicked.connect(self.gotoBenchmarking)
        self.helpbutton.clicked.connect(self.gotoPage)
        arr = self.db.getByQuery(query = {'name': 'None'})
        self.comboBox.addItems(arr[0]['templates'])

    def gotoPage(self):
        webbrowser.open("https://sih-grind.github.io/Help-Page/")

    def Harden(self):
        temp = self.comboBox.currentText()
        hard = hardener(self.sudo)
        output = hard.harden(temp)
        self.textBrowser.setText("\n".join(output))
        remove_ansi_escape_codes()

    def gotoBenchmarking(self):
        second = scaninf()
        third = warnings()
        fourth = suggestions()
        benchmarking=Ui_benchmarking(second, third, fourth,self.sudo)
        widget1.addWidget(benchmarking)
        widget1.setCurrentWidget(benchmarking)

    def gotoAdvanced(self):
        process = sp.Popen([f'sudo -S ufw status numbered'], stdin = sp.PIPE, stdout=sp.PIPE, shell=True)
        output, error = process.communicate("chai@1234".encode())
        process.wait()
        hardening=Ui_hardeningadvanced(output.decode(),self.sudo)
        widget1.addWidget(hardening)
        widget1.setCurrentWidget(hardening)

    def Save(self):
        #remove orphan packages
        #yes
        settings = {
          "pwdp":{
             "bool": "None",
             "args": "None",
             "id": 326724853050043943
          },
          "rmpk":{
             "bool": "True",
             "args": "None",
             "id": 332229282697495453
          },
          "ufwI":{
             "bool": "True",
             "args": "None",
             "id": 256018396983239556
          },
          "ufwE":{
             "bool": "None",
             "args": "None",
             "id": 213546050186360511
          },
          "ufwD":{
             "bool": "None",
             "args": "None",
             "id": 194594876564861602
          },
          "f2bE":{
             "name": "f2bE",
             "bool": "True",
             "args": "None",
             "id": 174149946064893431
          },
          "f2bD":{
             "bool": "None",
             "args": "None",
             "id": 255414737350607595
          },
          "usbE":{
             "bool": "None",
             "args": "None",
             "id": 263018632224000542
          },
          "ufwS":{
             "bool": "None",
             "args": "None",
             "id": 124601468034890564
          },
          "ufwBP":{
             
             "bool": "None",
             "args": "None",
             "id": 451361526694374776
          },
          "ufwAP":{
             "bool": "None",
             "args": "None",
             "id": 326362207710101556
          },
            "ufwAI":{
             "bool": "True",
             "args": "203.0.56.90",
             "id": 156032388352505362
          },
         "ufwBI":{
             "bool": "True",
             "args": "203.0.56.89",
             "id": 156384783488920966
          },
          "ufwDel":{
             "bool": "True",
             "args": "25",
             "id": 227570143566747332
          },
          "torD":{
             "bool": "True",
             "args": "None",
             "id": 279745690016785813
          },
          "sshp":{
             "bool": "True",
             "args": "2200",
             "id": 249746520959275740
          },
          "sshPAE":{
             "bool": "True",
             "args": "None",
             "id": 751891375988278035
          },
          "sshPAD":{
             "bool": "None",
             "args": "None",
             "id": 173213925518526525
          },
          "sshRE":{
             "bool": "True",
             "args": "None",
             "id": 100183796493969160
          },
          "sshRD":{
             "bool": "None",
             "args": "None",
             "id": 181500378830133344
          },
           "sshXFE":{
             "bool": "True",
             "args": "None",
             "id": 908020822052418092
          },
          "sshXFD":{
             "bool": "None",
             "args": "None",
             "id": 491140407706701361
          },
        }
        if self.rupyes.isChecked()==True:
            settings['rmpk']['bool'] = 'True'
        #no
        elif self.rupno.isChecked()==True:
            settings['rmpk']['bool'] = 'None'
        
        #password policies
        #weak
        if self.ppyes.isChecked()==True:
            settings['pwdp']['bool'] = 'None'
        #moderate
        elif self.ppno.isChecked()==True:
            settings['pwdp']['bool'] = 'None'
        #strong
        elif self.ppno_2.isChecked()==True:
            settings['pwdp']['bool'] = 'True'
        #ufw
        #enable
        if self.ufwyes.isChecked()==True:
            settings['ufwI']['bool'] = 'True'
            #self.db.updateByQuery({'name':'ufwE'},{'bool':'True'})
        #disable
        elif self.ufwno.isChecked()==True:
            settings['ufwI']['bool'] = 'None'
            settings['ufwE']['bool'] = 'None'
            settings['ufwD']['bool'] = 'True'
        
        #fail2ban
        #enable
        if self.fail2banyes.isChecked()==True:
            settings['f2bE']['bool'] = 'True'
        #disable
        elif self.fail2banno.isChecked()==True:
            settings['f2bD']['bool'] = 'True'
        
        #usb storage
        #enable
        if self.usbsayes.isChecked()==True:
            settings['usbE']['bool'] = 'True'
        #disable
        elif self.usbno.isChecked()==True:
            settings['usbE']['bool'] = 'None'
        #tor
        #enable
        if self.usbyes.isChecked()==True:
            settings['torD']['bool'] = 'True'
        #disable
        elif self.usbno_2.isChecked()==True:
            settings['torD']['bool'] = 'None'

        if(self.db.getByQuery({'name':self.lineEdit.text()})):
            self.db.update({'name':self.lineEdit.text()},{'name': self.lineEdit.text(),'settings': settings, 'templates':[]})
        else:
            self.db.add({'name': self.lineEdit.text(),'settings': settings, 'templates':[]})
            self.comboBox.addItem(self.lineEdit.text())
            arr = self.db.getByQuery(query = {'name': 'None'})
            arr = (arr[0]['templates'])
            arr.append(self.lineEdit.text())
            self.db.updateByQuery({'name':'None'}, {'name': 'None','settings': {}, 'templates': arr})

    def gotoHome(self):
        f = sysinf()
        s = scaninf()
        home = Ui_home(f,s[0],self.sudo)
        widget1.addWidget(home)
        widget1.setCurrentWidget(home)

class Ui_hardeningadvanced(QDialog):
    def __init__(self, rules, su):
        self.db = ps.getDb('bool.json')
        self.sudo = su
        super(Ui_hardeningadvanced,self).__init__()
        loadUi("network.ui",self)
        self.homebutton.clicked.connect(self.gotoHome)
        self.textBrowser.setText(rules)
        arr = self.db.getByQuery(query = {'name': 'None'})
        self.comboBox.addItems(arr[0]['templates'])
        self.textBrowser.setFont(QFont('Segoe UI Semilight',12))
        self.benchmarkingbuttton.clicked.connect(self.gotoBenchmarking)
        self.hardeningbutton.clicked.connect(self.gotoHardening)
        self.pushButton.clicked.connect(self.configAD)
        self.helpbutton.clicked.connect(self.gotoPage)
        self.pushButton_2.clicked.connect(self.applyNetwork)

    def gotoPage(self):
        webbrowser.open("https://sih-grind.github.io/Help-Page/")

    def configAD(self):
        arr = self.db.getByQuery(query = {'name': self.comboBox.currentText()})
        settings = arr[0]['settings']
        #ports
        if self.lineEdit.text():
            if self.radioButton.isChecked()==True:
                settings['ufwAP']['bool'] = 'True'
                settings['ufwAP']['args'] = self.lineEdit.text()
            elif self.radioButton_2.isChecked()==True:
                settings['ufwBP']['bool'] = 'True'
                settings['ufwBP']['args'] = self.lineEdit.text()
        else:
            settings['ufwAP']['bool'] = 'None'
            settings['ufwAP']['args'] = 'None'
            settings['ufwBP']['bool'] = 'None'
            settings['ufwBP']['args'] = 'None'

        #block ips
        if self.lineEdit_2.text():
            settings['ufwBI']['bool'] = 'True'
            settings['ufwBI']['args'] = self.lineEdit_2.text()
        #whitelist ips
        if self.lineEdit_3.text():
            settings['ufwAI']['bool'] = 'True'
            settings['ufwAI']['args'] = self.lineEdit_3.text()
        if self.lineEdit_4.text():
            settings['ufwDel']['bool'] = 'True'
            settings['ufwDel']['args'] = self.lineEdit_4.text()
        #ssh ports
        ssh_ports=self.lineEdit_5.text()
        if ssh_ports:
            settings['sshp']['bool'] = 'True'
            settings['sshp']['args'] = ssh_ports
        #Permit Root Login
        #enable
        if self.radioButton_3.isChecked()==True:
            settings['sshRE']['bool'] = 'True'
            settings['sshRE']['args'] = 'None'
        #disable
        elif self.radioButton_4.isChecked()==True:
            settings['sshRD']['bool'] = 'True'
            settings['sshRD']['args'] = 'None'
        #Password Authentication
        #enable
        if self.radioButton_5.isChecked()==True:
            settings['sshPAE']['bool'] = 'True'
            settings['sshPAE']['args'] = 'None'
        #disable
        elif self.radioButton_6.isChecked()==True:
            settings['sshPAD']['bool'] = 'True'
            settings['sshPAD']['args'] = 'None'
        #X11 Forwarding
        #enable
        if self.radioButton_7.isChecked()==True:
            settings['sshXFE']['bool'] = 'True'
            settings['sshXFE']['args'] = 'None'
        #disable
        elif self.radioButton_8.isChecked()==True:
            settings['sshXFD']['bool'] = 'True'
            settings['sshXFD']['args'] = 'None'

        updated_data = {'name': self.comboBox.currentText(), 'settings': settings, 'templates':[]}
        self.db.updateByQuery(db_dataset={'name': self.comboBox.currentText()}, new_dataset = updated_data)

    def applyNetwork(self):
        settings = {
          "ufwBP":{
             "bool": "None",
             "args": "None",
             "id": 451361526694374776
          },
          "ufwAP":{
             "bool": "None",
             "args": "None",
             "id": 326362207710101556
          },
            "ufwAI":{
             "bool": "True",
             "args": "None",
             "id": 156032388352505362
          },
         "ufwBI":{
             "bool": "True",
             "args": "None",
             "id": 156384783488920966
          },
          "ufwDel":{
             "bool": "True",
             "args": "None",
             "id": 227570143566747332
          },
          "torD":{
             "bool": "True",
             "args": "None",
             "id": 279745690016785813
          },
          "sshp":{
             "bool": "True",
             "args": "None",
             "id": 249746520959275740
          },
          "sshPAE":{
             "bool": "True",
             "args": "None",
             "id": 751891375988278035
          },
          "sshPAD":{
             "bool": "None",
             "args": "None",
             "id": 173213925518526525
          },
          "sshRE":{
             "bool": "True",
             "args": "None",
             "id": 100183796493969160
          },
          "sshRD":{
             "bool": "None",
             "args": "None",
             "id": 181500378830133344
          },
           "sshXFE":{
             "bool": "True",
             "args": "None",
             "id": 908020822052418092
          },
          "sshXFD":{
             "bool": "None",
             "args": "None",
             "id": 491140407706701361
          },
        }
        #ports
        if self.lineEdit.text():
            if self.radioButton.isChecked()==True:
                settings['ufwAP']['bool'] = 'True'
                settings['ufwAP']['args'] = self.lineEdit.text()
            elif self.radioButton_2.isChecked()==True:
                settings['ufwBP']['bool'] = 'True'
                settings['ufwBP']['args'] = self.lineEdit.text()
        else:
            settings['ufwAP']['bool'] = 'None'
            settings['ufwAP']['args'] = 'None'
            settings['ufwBP']['bool'] = 'None'
            settings['ufwBP']['args'] = 'None'

        #block ips
        if self.lineEdit_2.text():
            settings['ufwBI']['bool'] = 'True'
            settings['ufwBI']['args'] = self.lineEdit_2.text()
        #whitelist ips
        if self.lineEdit_3.text():
            settings['ufwAI']['bool'] = 'True'
            settings['ufwAI']['args'] = self.lineEdit_3.text()
        if self.lineEdit_4.text():
            settings['ufwDel']['bool'] = 'True'
            settings['ufwDel']['args'] = self.lineEdit_4.text()
        #ssh ports
        ssh_ports=self.lineEdit_5.text()
        if ssh_ports:
            settings['sshp']['bool'] = 'True'
            settings['sshp']['args'] = ssh_ports
        #Permit Root Login
        #enable
        if self.radioButton_3.isChecked()==True:
            settings['sshRE']['bool'] = 'True'
            settings['sshRE']['args'] = 'None'
        #disable
        elif self.radioButton_4.isChecked()==True:
            settings['sshRD']['bool'] = 'True'
            settings['sshRD']['args'] = 'None'
        #Password Authentication
        #enable
        if self.radioButton_5.isChecked()==True:
            settings['sshPAE']['bool'] = 'True'
            settings['sshPAE']['args'] = 'None'
        #disable
        elif self.radioButton_6.isChecked()==True:
            settings['sshPAD']['bool'] = 'True'
            settings['sshPAD']['args'] = 'None'
        #X11 Forwarding
        #enable
        if self.radioButton_7.isChecked()==True:
            settings['sshXFE']['bool'] = 'True'
            settings['sshXFE']['args'] = 'None'
        #disable
        elif self.radioButton_8.isChecked()==True:
            settings['sshXFD']['bool'] = 'True'
            settings['sshXFD']['args'] = 'None'

        updated_data = {'name': 'Network', 'settings': settings, 'templates':[]}
        self.db.updateByQuery(db_dataset={'name': 'Network'}, new_dataset = updated_data)
        hard = hardener(self.sudo)
        output = hard.harden('Network')
        remove_ansi_escape_codes()

    def gotoHome(self):
        f = sysinf()
        s = scaninf()
        home = Ui_home(f,s[0],self.sudo)
        widget1.addWidget(home)
        widget1.setCurrentWidget(home)

    def gotoBenchmarking(self):
        second = scaninf()
        third = warnings()
        fourth = suggestions()
        benchmarking=Ui_benchmarking(second, third, fourth,self.sudo)
        widget1.addWidget(benchmarking)
        widget1.setCurrentWidget(benchmarking)

    def gotoHardening(self):
        hardening=Ui_Hardening(self.sudo)
        widget1.addWidget(hardening)
        widget1.setCurrentWidget(hardening)


#hard = hardener()
remove_ansi_escape_codes()
makeDB()
first = sysinf()
second = scaninf()
third = warnings()
fourth = suggestions()
app = QApplication(sys.argv)
widget1=QtWidgets.QStackedWidget()

ui_openingpage=Ui_openingpage()
ui_registrationpage=Ui_registration()
ui_home=Ui_home(first, second[0], "None")
ui_benchmarking=Ui_benchmarking(second, third, fourth, "None")
ui_hardening=Ui_Hardening("None")
process = sp.Popen([f'sudo -S ufw status numbered'], stdin = sp.PIPE, stdout=sp.PIPE, shell=True)
output, error = process.communicate("chai@1234".encode())
process.wait()
ui_hardeningadvanced=Ui_hardeningadvanced(output.decode(),"None")

widget1.addWidget(ui_openingpage)
widget1.addWidget(ui_registrationpage)
widget1.addWidget(ui_home)
widget1.addWidget(ui_benchmarking)
widget1.addWidget(ui_hardening)
widget1.addWidget(ui_hardeningadvanced)

widget1.setFixedWidth(1220)
widget1.setFixedHeight(529)



widget1.show()


try:
    sys.exit(app.exec())
except Exception as e:
    print("An error occurred:", str(e))
